name: Changelog
on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Generate release changelog'
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
