name: CI

on:
  push:
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - 'apps/docs/**'
      - '.github/**'
      - '**/*.md'
  pull_request:
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - 'apps/docs/**'
      - '.github/**'
      - '**/*.md'
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run library build
        run: npx nx run signal-utils:build

      - name: Run tests
        run: npx nx run signal-utils:test

      - name: Run demo app build
        run: npx nx run demo:build
